<?php
// Helper
if (!function_exists('cityConfig')) {
    function cityConfig(string $key, string $name, string $province, float $lat, float $lng, string $region, array $nearby = [], array $extra = []): array {
        $slug = 'jasa-pembuatan-website-'.str_replace(' ','-',strtolower($name)).'-murah';
        $kw   = $extra['kw'] ?? '';
        return array_merge([
            'key'         => $key,
            'name'        => $name,
            'province'    => $province,
            'slug'        => $slug,
            'lat'         => $lat,
            'lng'         => $lng,
            'geo_region'  => $region,
            'h1'          => "Jasa Pembuatan Website $name Murah, Profesional & Terpercaya",
            'title'       => "Jasa Pembuatan Website $name Murah & Profesional | HVM Digital",
            'description' => "Butuh jasa pembuatan website $name yang murah, profesional, dan terpercaya? HVM Digital solusinya. Konsultasi gratis, support 1 tahun. Hubungi kami!",
            'keywords'    => "jasa website $name, jasa pembuatan website $name, website $name murah, website $name terpercaya, website $name profesional, jasa website $name termurah, jasa website $name terbaik, $kw",
            'nearby'      => $nearby,
        ], $extra);
    }
}

return [
    'surabaya'   => cityConfig('surabaya','Surabaya','Jawa Timur',-7.2575,112.7521,'ID-JI',
        ['Rungkut','Gubeng','Wonokromo','Wiyung','Benowo','Kenjeran','Mulyorejo','Sambikerep','Lakarsantri','Bulak'],
        ['is_hq'=>true]),
    'jakarta'    => cityConfig('jakarta','Jakarta','DKI Jakarta',-6.2088,106.8456,'ID-JK',
        ['Kebayoran','Menteng','Kemayoran','Cengkareng','Penjaringan','Tebet','Pulo Gadung','Cilincing']),
    'malang'     => cityConfig('malang','Malang','Jawa Timur',-7.9797,112.6304,'ID-JI',
        ['Lowokwaru','Sukun','Klojen','Blimbing','Kedungkandang']),
    'bandung'    => cityConfig('bandung','Bandung','Jawa Barat',-6.9175,107.6191,'ID-JB',
        ['Coblong','Cicendo','Andir','Sukajadi','Antapani','Buahbatu','Gedebage']),
    'semarang'   => cityConfig('semarang','Semarang','Jawa Tengah',-6.9932,110.4203,'ID-JT',
        ['Banyumanik','Pedurungan','Tembalang','Candisari','Gayamsari','Genuk']),
    'yogyakarta' => cityConfig('yogyakarta','Yogyakarta','DI Yogyakarta',-7.7956,110.3695,'ID-YO',
        ['Gondokusuman','Mergangsan','Jetis','Wirobrajan','Kotagede','Umbulharjo']),
    'solo'       => cityConfig('solo','Solo','Jawa Tengah',-7.5755,110.8243,'ID-JT',
        ['Banjarsari','Laweyan','Serengan','Pasar Kliwon','Jebres']),
    'bekasi'     => cityConfig('bekasi','Bekasi','Jawa Barat',-6.2349,106.9896,'ID-JB',
        ['Bekasi Timur','Bekasi Barat','Bekasi Utara','Bekasi Selatan','Rawalumbu','Mustikajaya','Pondok Melati']),
    'palembang'  => cityConfig('palembang','Palembang','Sumatera Selatan',-2.9761,104.7754,'ID-SS',
        ['Ilir Barat','Ilir Timur','Seberang Ulu','Bukit Kecil','Gandus']),
    'denpasar'   => cityConfig('denpasar','Bali','Bali',-8.6705,115.2126,'ID-BA',
        ['Denpasar Utara','Denpasar Selatan','Denpasar Timur','Denpasar Barat','Kuta','Seminyak','Ubud','Gianyar','Tabanan'],
        ['kw'=>'jasa website bali, website bali murah']),
    'banyuwangi' => cityConfig('banyuwangi','Banyuwangi','Jawa Timur',-8.2192,114.3692,'ID-JI',
        ['Banyuwangi Kota','Glagah','Rogojampi','Genteng','Gambiran']),
    'gresik'     => cityConfig('gresik','Gresik','Jawa Timur',-7.1575,112.6550,'ID-JI',
        ['Gresik Kota','Kebomas','Manyar','Driyorejo','Menganti','Benjeng']),
    'sidoarjo'   => cityConfig('sidoarjo','Sidoarjo','Jawa Timur',-7.4478,112.7183,'ID-JI',
        ['Sidoarjo Kota','Waru','Taman','Gedangan','Buduran','Candi','Porong']),
    'lamongan'   => cityConfig('lamongan','Lamongan','Jawa Timur',-7.1167,112.4167,'ID-JI',
        ['Lamongan Kota','Babat','Paciran','Brondong','Bluluk']),
    'ngawi'      => cityConfig('ngawi','Ngawi','Jawa Timur',-7.4044,111.4502,'ID-JI',
        ['Ngawi Kota','Paron','Geneng','Mantingan','Kedunggalar']),
    'purwokerto' => cityConfig('purwokerto','Purwokerto','Jawa Tengah',-7.4222,109.2385,'ID-JT',
        ['Purwokerto Utara','Purwokerto Selatan','Purwokerto Barat','Purwokerto Timur','Sokaraja']),
    'medan'      => cityConfig('medan','Medan','Sumatera Utara',3.5952,98.6722,'ID-SU',
        ['Medan Baru','Medan Kota','Medan Sunggal','Medan Helvetia','Medan Petisah','Medan Amplas','Medan Belawan']),
    'samarinda'  => cityConfig('samarinda','Samarinda','Kalimantan Timur',-0.5022,117.1536,'ID-KI',
        ['Samarinda Ulu','Samarinda Kota','Sungai Pinang','Loa Janan Ilir','Sambutan']),
    'makassar'   => cityConfig('makassar','Makassar','Sulawesi Selatan',-5.1477,119.4327,'ID-SN',
        ['Biringkanaya','Tamalanrea','Panakkukang','Rappocini','Manggala','Mariso','Bontoala']),
    'balikpapan' => cityConfig('balikpapan','Balikpapan','Kalimantan Timur',-1.2654,116.8312,'ID-KI',
        ['Balikpapan Utara','Balikpapan Selatan','Balikpapan Timur','Balikpapan Barat','Balikpapan Kota']),
    'pekanbaru'  => cityConfig('pekanbaru','Pekanbaru','Riau',0.5071,101.4478,'ID-RI',
        ['Tampan','Marpoyan Damai','Bukit Raya','Sail','Tenayan Raya','Rumbai']),
    'batam'      => cityConfig('batam','Batam','Kepulauan Riau',1.0456,104.0305,'ID-KR',
        ['Batam Kota','Sekupang','Nongsa','Batu Aji','Sagulung','Lubuk Baja']),
    'padang'     => cityConfig('padang','Padang','Sumatera Barat',-0.9471,100.4172,'ID-SB',
        ['Kuranji','Nanggalo','Padang Utara','Padang Selatan','Padang Timur','Padang Barat']),
    'manado'     => cityConfig('manado','Manado','Sulawesi Utara',1.4748,124.8421,'ID-SA',
        ['Wenang','Tikala','Singkil','Tuminting','Mapanget','Malalayang','Sario']),
    'banjarmasin'=> cityConfig('banjarmasin','Banjarmasin','Kalimantan Selatan',-3.3186,114.5944,'ID-KS',
        ['Banjarmasin Utara','Banjarmasin Selatan','Banjarmasin Timur','Banjarmasin Barat','Banjarmasin Tengah']),
    'pontianak'  => cityConfig('pontianak','Pontianak','Kalimantan Barat',-0.0263,109.3425,'ID-KB',
        ['Pontianak Kota','Pontianak Utara','Pontianak Selatan','Pontianak Timur','Pontianak Tenggara','Pontianak Barat']),
    'mataram'    => cityConfig('mataram','Mataram','NTB',-8.5833,116.1167,'ID-NB',
        ['Ampenan','Cakranegara','Mataram Kota','Sandubaya','Selaparang','Sekarbela']),
    'bogor'      => cityConfig('bogor','Bogor','Jawa Barat',-6.5971,106.7960,'ID-JB',
        ['Bogor Utara','Bogor Selatan','Bogor Timur','Bogor Barat','Bogor Tengah','Tanah Sareal']),
    'depok'      => cityConfig('depok','Depok','Jawa Barat',-6.4025,106.7942,'ID-JB',
        ['Beji','Cimanggis','Cinere','Limo','Pancoran Mas','Sawangan','Sukmajaya']),
    'tangerang'  => cityConfig('tangerang','Tangerang','Banten',-6.1702,106.6402,'ID-BT',
        ['Tangerang Kota','Cipondoh','Batuceper','Cibodas','Karawaci','Periuk','Pinang']),
    'cirebon'    => cityConfig('cirebon','Cirebon','Jawa Barat',-6.7063,108.5570,'ID-JB',
        ['Kejaksan','Kesambi','Lemahwungkuk','Pekalipan','Harjamukti']),
    'kediri'     => cityConfig('kediri','Kediri','Jawa Timur',-7.8166,112.0110,'ID-JI',
        ['Mojoroto','Kota Kediri','Pesantren']),
    'madiun'     => cityConfig('madiun','Madiun','Jawa Timur',-7.6298,111.5240,'ID-JI',
        ['Manguharjo','Taman','Kartoharjo']),
    'jember'     => cityConfig('jember','Jember','Jawa Timur',-8.1717,113.7025,'ID-JI',
        ['Patrang','Sumbersari','Kaliwates','Pakusari','Kencong','Ambulu']),
    'kupang'     => cityConfig('kupang','Kupang','NTT',-10.1772,123.6070,'ID-NT',
        ['Kelapa Lima','Maulafa','Alak','Oebobo','Kota Raja']),
    'jayapura'   => cityConfig('jayapura','Jayapura','Papua',-2.5916,140.6690,'ID-PA',
        ['Abepura','Jayapura Utara','Jayapura Selatan','Muara Tami','Heram']),
];
